-- Criando Base de Dados
CREATE DATABASE IF NOT EXISTS `Registro_Database`;

-- Usando Base de Dados
USE `Registro_Database`;

-- Criando Tabela - EMPRESA
CREATE TABLE IF NOT EXISTS `EMPRESA` (
    `CNPJ` CHAR(14) NOT NULL,
    `CODIGO_EMPRESA` INT NOT NULL AUTO_INCREMENT,
    `NOMEFANTASIA` VARCHAR(35) NOT NULL,
    `CEP` INT(8) NOT NULL,
    `UF` CHAR(2) NOT NULL,
    `E-MAIL` VARCHAR(55) NOT NULL,
    `CIDADE` VARCHAR(35) NOT NULL,
    `BAIRRO` VARCHAR(35) NOT NULL,
    `LOGRADOURO` VARCHAR(100) NOT NULL,
    `NUMERO` INT(10) NOT NULL,
    `COMPLEMENTO` VARCHAR(50),
    `DATACRIACAO` DATE NOT NULL,
    PRIMARY KEY (`CODIGO_EMPRESA`),
    UNIQUE KEY (`CNPJ`)
    
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


-- Criando Tabela - COLABORADOR
CREATE TABLE IF NOT EXISTS `COLABORADOR` (
    `MATRICULA` VARCHAR(14) NOT NULL, -- ALTERAR PARA INT
    `CNPJ_EMPRESA` CHAR(14) NOT NULL,
    `NOME` VARCHAR(100) NOT NULL,
    `CPF` CHAR(11) NOT NULL,
    `RG` CHAR(9) NOT NULL,
    `DATA_NASCIMENTO` DATE NOT NULL,
    `DATA_ADMISSAO` DATE NOT NULL,
    `NIS` CHAR(11) NOT NULL,
    `CTPS` CHAR(11) NOT NULL,
    `CARGA_HORARIA` TIME NOT NULL,
    `CARGO` VARCHAR(40) NOT NULL,
    `IMAGEM` MEDIUMBLOB DEFAULT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Criando Chave Primária
ALTER TABLE `COLABORADOR` ADD CONSTRAINT `PK_COLABORADOR_MATRICULA_CNPJ` 
PRIMARY KEY (`MATRICULA`, `CNPJ_EMPRESA`);

-- Criando Chave Estrangeira para EMPRESA
ALTER TABLE `COLABORADOR` ADD CONSTRAINT `FK_COLABORADOR_CNPJ_EMPRESA` 
FOREIGN KEY (`CNPJ_EMPRESA`) 
REFERENCES `EMPRESA`(`CNPJ`) 
ON DELETE RESTRICT ON UPDATE CASCADE;

-- Criando Tabela - USUARIO_COLABORADOR
CREATE TABLE IF NOT EXISTS `USUARIO_COLABORADOR` (
    `USUARIO_ID` VARCHAR(14),
    `SENHA` VARCHAR(100) NOT NULL,
    `ADM` BOOLEAN NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Criando Chave Primária
ALTER TABLE `USUARIO_COLABORADOR` ADD CONSTRAINT `PK_USUARIO_COLABORADOR_ID` PRIMARY KEY (`USUARIO_ID`);

-- Criando Chaves Estrangeiras para USUARIO_COLABORADOR
-- Referência para COLABORADOR
ALTER TABLE `USUARIO_COLABORADOR` ADD CONSTRAINT `FK_USUARIO_COLABORADOR` 
FOREIGN KEY (`USUARIO_ID`) 
REFERENCES `COLABORADOR`(`MATRICULA`) 
ON DELETE CASCADE ON UPDATE CASCADE;

-- Criando Tabela - USUARIO_EMPRESA
CREATE TABLE IF NOT EXISTS `USUARIO_EMPRESA` (
    `USUARIO_ID` VARCHAR(14),
    `SENHA` VARCHAR(100) NOT NULL,
    `ADM` BOOLEAN NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Criando Chave Primária
ALTER TABLE `USUARIO_EMPRESA` ADD CONSTRAINT `PK_USUARIO_EMPRESA_ID` PRIMARY KEY (`USUARIO_ID`);

-- Criando Chaves Estrangeiras para USUARIO_EMPRESA
-- Referência para EMPRESA
ALTER TABLE `USUARIO_EMPRESA` ADD CONSTRAINT `FK_USUARIO_EMPRESA` 
FOREIGN KEY (`USUARIO_ID`) 
REFERENCES `EMPRESA`(`CNPJ`) 
ON DELETE RESTRICT ON UPDATE CASCADE;

-- Criando Tabela - REGISTRO_PONTO
CREATE TABLE IF NOT EXISTS `REGISTRO_PONTO` (
    `MATRICULA` VARCHAR(14) NOT NULL,
    `CNPJ_EMPRESA` CHAR(14) NOT NULL,
    `DATA_PONTO` DATETIME NOT NULL

) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Criando Chave Primária
ALTER TABLE `REGISTRO_PONTO` ADD CONSTRAINT `PK_REGISTRO_PONTO` 
PRIMARY KEY (`MATRICULA`, `CNPJ_EMPRESA`, `DATA_PONTO`);

-- Criando Chaves Estrangeiras para REGISTRO_PONTO
-- Referência para COLABORADOR
-- Alterar esta parte do seu script:
ALTER TABLE `REGISTRO_PONTO` ADD CONSTRAINT `FK_REG_PONTO_COLAB` 
FOREIGN KEY (`MATRICULA`, `CNPJ_EMPRESA`) 
REFERENCES `COLABORADOR`(`MATRICULA`, `CNPJ_EMPRESA`) 
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `REGISTRO_PONTO` ADD CONSTRAINT `FK_REG_PONTO_EMP` 
FOREIGN KEY (`CNPJ_EMPRESA`) 
REFERENCES `EMPRESA`(`CNPJ`) 
ON DELETE RESTRICT ON UPDATE CASCADE;